site_name: Simple-CDD-YAML Documentation
site_url: https://swvanbuuren.github.io/simple-cdd-yaml/
repo_url: https://github.com/swvanbuuren/simple-cdd-yaml
repo_name: swvanbuuren/simple-cdd-yaml

theme:
  name: material
  features:
  - navigation.sections
  - navigation.tabs
  - navigation.indexes
  - content.code.annotate
  - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences

nav:
  - Simple-CDD-YAML:
    - index.md
    - Introduction: introduction.md
    - Getting started: getting_started.md
    - Installation: installation.md
    - Examples: examples.md
  - Build images:
    - build-images/index.md
    - Build in Docker: build-images/build-in-docker.md
    - Test on Qemu with UEFI: build-images/test-on-qemu-with-uefi.md
    - Build with Debos: build-images/build-with-debos.md
  - Actions:
    - actions/index.md
    - Recipe Action: actions/recipe.md
    - Conf Action: actions/conf.md
    - Preseed Action: actions/preseed.md
    - Apt Action: actions/apt.md
    - Run Action: actions/run.md
    - Overlay Action: actions/overlay.md
    - Extra Action: actions/extra.md
    - Downloads Action: actions/downloads.md
    - Debos Action: actions/debos.md
  - Code Reference:
    - reference/index.md
    - Simple-CDD-YAML: reference/simple_cdd_yaml.md
    - Recipe Interpreter: reference/recipe_interpreter.md
    - Actions: reference/actions.md
    - YAML tools: reference/yaml_tools.md
