site_name: Simple-CDD-YAML Documentation
site_url: https://swvanbuuren.github.io/simple-cdd-yaml
theme:
  name: material
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
